// Generated by tools/generate_element_package_registrations.py.
// Do not edit by hand.
#include "GeneratedElementPackageRegistrations.h"

#include "../visuals/LayerFactory.h"

#include <memory>
#include <stdexcept>
#include <string>
#include <utility>

std::unique_ptr<Layer> synaptomeCreateElementPackage_examples_signal_bloom();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_chladni_plate();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_dendritic_crystal();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_differential_growth();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_elastic_lattice();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_gerstner_ocean();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_magnetic_dipoles();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_phase_lattice();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_sand_ripples();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_strange_attractor();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_voronoi_foam();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_vortex_advection();
std::unique_ptr<Layer> synaptomeCreateElementPackage_show_wave_tank();

namespace synaptome::runtime {
namespace {

using synaptome::element::ActionDescriptor;
using synaptome::element::ElementDescriptor;
using synaptome::element::ElementKind;
using synaptome::element::ElementTypeContract;
using synaptome::element::ParameterDeclaration;
using synaptome::element::ParameterDeprecation;
using synaptome::element::ParameterGroupDeclaration;
using synaptome::element::ParameterKind;
using synaptome::element::ParameterOption;
using synaptome::element::ParameterOptionSource;
using synaptome::element::ParameterRange;

constexpr GeneratedElementPackageRegistration kRegistrations[] = {
    {
        "examples.signal_bloom",
        "0.1.0",
        "0.1.0",
        "example.signalBloom",
        "visual",
        "bind-only",
        "examples.signal_bloom",
        "examples.signal_bloom",
        "source/register_signal_bloom.cpp",
        "39e6e7934d09689bd1a952e2d040f3a36ebdf595a47446778d1745a2fcdb00de",
    },
    {
        "show.chladni_plate",
        "0.1.0",
        "0.1.0",
        "show.chladniPlate",
        "visual",
        "bind-only",
        "show.chladni_plate",
        "show.chladni_plate",
        "source/register_chladni_plate.cpp",
        "15a9335fa1d248ccf80456bc2ae5690f1384f00384132cceeefd9c79086ac19f",
    },
    {
        "show.dendritic_crystal",
        "0.1.0",
        "0.1.0",
        "show.dendriticCrystal",
        "visual",
        "bind-only",
        "show.dendritic_crystal",
        "show.dendritic_crystal",
        "source/register_dendritic_crystal.cpp",
        "43aaa5e82dc64c72906462a4e5ab49b012832c86f3bc8cbe5d7fbda1b9822879",
    },
    {
        "show.differential_growth",
        "0.1.0",
        "0.1.0",
        "show.differentialGrowth",
        "visual",
        "bind-only",
        "show.differential_growth",
        "show.differential_growth",
        "source/register_differential_growth.cpp",
        "a19ddf8919c6d193e6a761eb980f606e43e24ccbbdbb4737bd8766ca2d2c001c",
    },
    {
        "show.elastic_lattice",
        "0.1.0",
        "0.1.0",
        "show.elasticLattice",
        "visual",
        "bind-only",
        "show.elastic_lattice",
        "show.elastic_lattice",
        "source/register_elastic_lattice.cpp",
        "beb0153e78f4c34544af2505c1cc84e47f5b1b817ad56e333c89efbde1da6cd6",
    },
    {
        "show.gerstner_ocean",
        "0.1.0",
        "0.1.0",
        "show.gerstnerOcean",
        "visual",
        "bind-only",
        "show.gerstner_ocean",
        "show.gerstner_ocean",
        "source/register_gerstner_ocean.cpp",
        "3bdc0448253157f9bbe935032b66d433e35d2b79af55be83036f8c5ae9c3b852",
    },
    {
        "show.magnetic_dipoles",
        "0.1.0",
        "0.1.0",
        "show.magneticDipoles",
        "visual",
        "bind-only",
        "show.magnetic_dipoles",
        "show.magnetic_dipoles",
        "source/register_magnetic_dipoles.cpp",
        "f52ad94b59201b9d35340993eef0d06773431e83c2360244da83785eb1ac54b8",
    },
    {
        "show.phase_lattice",
        "0.1.0",
        "0.1.0",
        "show.phaseLattice",
        "visual",
        "bind-only",
        "show.phase_lattice",
        "show.phase_lattice",
        "source/register_phase_lattice.cpp",
        "918b5cebb4f4a3faa7feaeafb977da549de8115a88a4b48200ed32f72b00b51e",
    },
    {
        "show.sand_ripples",
        "0.1.0",
        "0.1.0",
        "show.sandRipples",
        "visual",
        "bind-only",
        "show.sand_ripples",
        "show.sand_ripples",
        "source/register_sand_ripples.cpp",
        "76307bbc79aba7b24f834a79b34421d72bbd47c94086f2f75e15f5544dc62097",
    },
    {
        "show.strange_attractor",
        "0.1.0",
        "0.1.0",
        "show.strangeAttractor",
        "visual",
        "bind-only",
        "show.strange_attractor",
        "show.strange_attractor",
        "source/register_strange_attractor.cpp",
        "55b58e6186ac4594421d29fbb0ca983e9f1348ab2c831c7ef1c4a0682965e81a",
    },
    {
        "show.voronoi_foam",
        "0.1.0",
        "0.1.0",
        "show.voronoiFoam",
        "visual",
        "bind-only",
        "show.voronoi_foam",
        "show.voronoi_foam",
        "source/register_voronoi_foam.cpp",
        "5a4da4b918b01f57586eef55fb38974b726d8f25644420f9a254477c13ebc5a4",
    },
    {
        "show.vortex_advection",
        "0.1.0",
        "0.1.0",
        "show.vortexAdvection",
        "visual",
        "bind-only",
        "show.vortex_advection",
        "show.vortex_advection",
        "source/register_vortex_advection.cpp",
        "e92194157eaac9fb3499fe51c1da1169facb8613b7e995d58b7af1579a599a73",
    },
    {
        "show.wave_tank",
        "0.1.0",
        "0.1.0",
        "show.waveTank",
        "visual",
        "bind-only",
        "show.wave_tank",
        "show.wave_tank",
        "source/register_wave_tank.cpp",
        "d7d420a59c7497b6987bf86c86c9d3d1683a2fbcce33c865a01ef6c593d3376f",
    },
};

ElementTypeContract generatedContract0() {
    ElementTypeContract contract;
    contract.element = ElementDescriptor{
        "example.signalBloom",
        ElementKind::Visual,
        {

        },
    };
    contract.parameters.groups = {
        ParameterGroupDeclaration{"example", "Example", ""},
        ParameterGroupDeclaration{"exampleMotion", "Example Motion", ""},
        ParameterGroupDeclaration{"exampleTransform", "Example Transform", ""},
        ParameterGroupDeclaration{"exampleColor", "Example Color", ""},
        ParameterGroupDeclaration{"exampleModulation", "Example Modulation", ""}
    };
    {
        ParameterDeclaration value;
        value.id = "visible";
        value.kind = ParameterKind::Bool;
        value.groupId = "example";
        value.label = "Visible";
        value.defaultValue = true;
        value.units = "";
        value.description = "Whether the layer contributes to the current slot.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "speed";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleMotion";
        value.label = "Speed";
        value.defaultValue = 0.649999976f;
        value.range = ParameterRange{0.0f, 4.0f, 0.00999999978f};
        value.units = "multiplier";
        value.description = "Local signal motion speed.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bpmSync";
        value.kind = ParameterKind::Bool;
        value.groupId = "exampleMotion";
        value.label = "BPM Sync";
        value.defaultValue = true;
        value.units = "";
        value.description = "Whether local motion follows the global transport BPM.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bpmMultiplier";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleMotion";
        value.label = "BPM Multiplier";
        value.defaultValue = 1.0f;
        value.range = ParameterRange{0.25f, 8.0f, 0.25f};
        value.units = "multiplier";
        value.description = "Multiplier applied to global transport BPM when sync is enabled. Browser inspection resolves the app-owned provider to labeled multiplier choices.";
        value.optionSource = ParameterOptionSource{"transport.bpmMultipliers", "multiplier", "label"};
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "scale";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleTransform";
        value.label = "Size";
        value.defaultValue = 0.819999993f;
        value.range = ParameterRange{0.100000001f, 2.0f, 0.00999999978f};
        value.units = "multiplier";
        value.description = "Layer-local visual scale.";
        value.options = {
            ParameterOption{0.5f, "Compact", "Reduce the layer footprint."},
            ParameterOption{0.819999993f, "Default", "Use the reviewed package scale."},
            ParameterOption{1.0f, "Full", "Use the full normalized layer scale."},
        };
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "rotationDeg";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleTransform";
        value.label = "Rotation";
        value.defaultValue = 0.0f;
        value.range = ParameterRange{-180.0f, 180.0f, 1.0f};
        value.units = "deg";
        value.description = "Layer-local rotation in degrees.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "alpha";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Alpha";
        value.defaultValue = 0.860000014f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Legacy layer-local alpha exposed by the current SDK example.";
        value.deprecation = ParameterDeprecation{"opacity", "New layers should prefer opacity/visibility naming, but this fixture preserves the current public SDK parameter."};
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "gain";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "Sensor Gain";
        value.defaultValue = 0.620000005f;
        value.range = ParameterRange{0.0f, 2.0f, 0.00999999978f};
        value.units = "multiplier";
        value.description = "Gain applied to generic input modulation.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "lineOpacity";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Line Opacity";
        value.defaultValue = 0.720000029f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Opacity for the signal line stroke.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "colorR";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Red";
        value.defaultValue = 0.119999997f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Primary color red channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "colorG";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Green";
        value.defaultValue = 0.779999971f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Primary color green channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "colorB";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Blue";
        value.defaultValue = 1.0f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Primary color blue channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bgColorR";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Background Red";
        value.defaultValue = 0.0199999996f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Background color red channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bgColorG";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Background Green";
        value.defaultValue = 0.0399999991f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Background color green channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bgColorB";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Background Blue";
        value.defaultValue = 0.0799999982f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Background color blue channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "xInput";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "X";
        value.defaultValue = 0.5f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00100000005f};
        value.units = "";
        value.description = "Generic horizontal modulation input.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "yInput";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "Y";
        value.defaultValue = 0.5f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00100000005f};
        value.units = "";
        value.description = "Generic vertical modulation input.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "speedInput";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "Speed";
        value.defaultValue = 0.0f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00100000005f};
        value.units = "";
        value.description = "Generic motion modulation input.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    return contract;
}

ElementTypeContract generatedContract1() {
    ElementTypeContract contract;
    contr