// Generated by tools/generate_element_package_registrations.py.
// Do not edit by hand.
#include "GeneratedElementPackageRegistrations.h"

#include "../visuals/LayerFactory.h"

#include <memory>
#include <stdexcept>
#include <string>
#include <utility>

std::unique_ptr<Layer> synaptomeCreateElementPackage_examples_signal_bloom();

namespace synaptome::runtime {
namespace {

using synaptome::element::ActionDescriptor;
using synaptome::element::ElementDescriptor;
using synaptome::element::ElementKind;
using synaptome::element::ElementTypeContract;
using synaptome::element::ParameterDeclaration;
using synaptome::element::ParameterDeprecation;
using synaptome::element::ParameterGroupDeclaration;
using synaptome::element::ParameterKind;
using synaptome::element::ParameterOption;
using synaptome::element::ParameterOptionSource;
using synaptome::element::ParameterRange;

constexpr GeneratedElementPackageRegistration kRegistrations[] = {
    {
        "examples.signal_bloom",
        "0.1.0",
        "0.1.0",
        "example.signalBloom",
        "visual",
        "bind-only",
        "examples.signal_bloom",
        "examples.signal_bloom",
        "source/register_signal_bloom.cpp",
        "39e6e7934d09689bd1a952e2d040f3a36ebdf595a47446778d1745a2fcdb00de",
    },
};

ElementTypeContract generatedContract0() {
    ElementTypeContract contract;
    contract.element = ElementDescriptor{
        "example.signalBloom",
        ElementKind::Visual,
        {

        },
    };
    contract.parameters.groups = {
        ParameterGroupDeclaration{"example", "Example", ""},
        ParameterGroupDeclaration{"exampleMotion", "Example Motion", ""},
        ParameterGroupDeclaration{"exampleTransform", "Example Transform", ""},
        ParameterGroupDeclaration{"exampleColor", "Example Color", ""},
        ParameterGroupDeclaration{"exampleModulation", "Example Modulation", ""}
    };
    {
        ParameterDeclaration value;
        value.id = "visible";
        value.kind = ParameterKind::Bool;
        value.groupId = "example";
        value.label = "Visible";
        value.defaultValue = true;
        value.units = "";
        value.description = "Whether the layer contributes to the current slot.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "speed";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleMotion";
        value.label = "Speed";
        value.defaultValue = 0.649999976f;
        value.range = ParameterRange{0.0f, 4.0f, 0.00999999978f};
        value.units = "multiplier";
        value.description = "Local signal motion speed.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bpmSync";
        value.kind = ParameterKind::Bool;
        value.groupId = "exampleMotion";
        value.label = "BPM Sync";
        value.defaultValue = true;
        value.units = "";
        value.description = "Whether local motion follows the global transport BPM.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bpmMultiplier";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleMotion";
        value.label = "BPM Multiplier";
        value.defaultValue = 1.0f;
        value.range = ParameterRange{0.25f, 8.0f, 0.25f};
        value.units = "multiplier";
        value.description = "Multiplier applied to global transport BPM when sync is enabled. Browser inspection resolves the app-owned provider to labeled multiplier choices.";
        value.optionSource = ParameterOptionSource{"transport.bpmMultipliers", "multiplier", "label"};
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "scale";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleTransform";
        value.label = "Size";
        value.defaultValue = 0.819999993f;
        value.range = ParameterRange{0.100000001f, 2.0f, 0.00999999978f};
        value.units = "multiplier";
        value.description = "Layer-local visual scale.";
        value.options = {
            ParameterOption{0.5f, "Compact", "Reduce the layer footprint."},
            ParameterOption{0.819999993f, "Default", "Use the reviewed package scale."},
            ParameterOption{1.0f, "Full", "Use the full normalized layer scale."},
        };
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "rotationDeg";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleTransform";
        value.label = "Rotation";
        value.defaultValue = 0.0f;
        value.range = ParameterRange{-180.0f, 180.0f, 1.0f};
        value.units = "deg";
        value.description = "Layer-local rotation in degrees.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "alpha";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Alpha";
        value.defaultValue = 0.860000014f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Legacy layer-local alpha exposed by the current SDK example.";
        value.deprecation = ParameterDeprecation{"opacity", "New layers should prefer opacity/visibility naming, but this fixture preserves the current public SDK parameter."};
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "gain";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "Sensor Gain";
        value.defaultValue = 0.620000005f;
        value.range = ParameterRange{0.0f, 2.0f, 0.00999999978f};
        value.units = "multiplier";
        value.description = "Gain applied to generic input modulation.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "lineOpacity";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Line Opacity";
        value.defaultValue = 0.720000029f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Opacity for the signal line stroke.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "colorR";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Red";
        value.defaultValue = 0.119999997f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Primary color red channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "colorG";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Green";
        value.defaultValue = 0.779999971f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Primary color green channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "colorB";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Blue";
        value.defaultValue = 1.0f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Primary color blue channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bgColorR";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Background Red";
        value.defaultValue = 0.0199999996f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Background color red channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bgColorG";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Background Green";
        value.defaultValue = 0.0399999991f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Background color green channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "bgColorB";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleColor";
        value.label = "Background Blue";
        value.defaultValue = 0.0799999982f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00999999978f};
        value.units = "";
        value.description = "Background color blue channel.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "xInput";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "X";
        value.defaultValue = 0.5f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00100000005f};
        value.units = "";
        value.description = "Generic horizontal modulation input.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "yInput";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "Y";
        value.defaultValue = 0.5f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00100000005f};
        value.units = "";
        value.description = "Generic vertical modulation input.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    {
        ParameterDeclaration value;
        value.id = "speedInput";
        value.kind = ParameterKind::Float;
        value.groupId = "exampleModulation";
        value.label = "Speed";
        value.defaultValue = 0.0f;
        value.range = ParameterRange{0.0f, 1.0f, 0.00100000005f};
        value.units = "";
        value.description = "Generic motion modulation input.";
        value.visible = true;
        contract.parameters.parameters.push_back(std::move(value));
    }
    return contract;
}


} // namespace

const GeneratedElementPackageRegistration*
generatedElementPackageRegistrations(std::size_t& count) noexcept {
    count = sizeof(kRegistrations) / sizeof(kRegistrations[0]);
    return kRegistrations;
}

void registerGeneratedElementPackages(LayerFactory& elementTypes) {
    if (elementTypes.contains("example.signalBloom")) {
        throw std::logic_error(
            "generated package type already registered: example.signalBloom");
    }
    elementTypes.registerType(
        generatedContract0(),
        [] { return synaptomeCreateElementPackage_examples_signal_bloom(); },
        LayerFactory::ParameterBindingMode::Explicit);
    if (!elementTypes.contains("example.signalBloom")) {
        throw std::logic_error(
            "generated registrar did not publish expected type: example.signalBloom");
    }
}

} // namespace synaptome::runtime
